#%RAML 1.0
title: Directory User Registration 
version: v1
baseUri: http://user-registration/
mediaType: application/json
    
types: 
  User:
    type: object
    properties: 
      url:
        type: string
        pattern: ^((http(s?))\:\/\/)?((([a-zA-Z0-9_\-]{2,}\.)+[a-zA-Z]{2,})|((?:(?:25[0-5]|2[0-4]\d|[01]\d\d|\d?\d)( ?(\.?\d)\.)){4}))(:[a-zA-Z0-9]+)?(\/[a-zA-Z0-9\-\._\?\,\'\/\\\+&amp;%\$#\=~]*)?$
      number?: string

/:
  get:
    description: Returns metadata associated with the directory
    responses: 
      200:
          
/users:
  post:
    description: Demo Create a user
    body:
      type: object
      properties:
        url:
          type: string
          pattern: ^((http(s?))\:\/\/)?((([a-zA-Z0-9_\-]{2,}\.)+[a-zA-Z]{2,})|((?:(?:25[0-5]|2[0-4]\d|[01]\d\d|\d?\d)( ?(\.?\d)\.)){4}))(:[a-zA-Z0-9]+)?(\/[a-zA-Z0-9\-\._\?\,\'\/\\\+&amp;%\$#\=~]*)?$
    responses:
      201:
        body:
          type: User
  /{number}:
    get:
      description: Look up User
      responses:
        200:
          body:
            type: User